version: '3'
services:
  database:
    container_name: database
    image: postgres:14-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6-alpine
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.22.4
    ports:
      - 8055:8055
    volumes:
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
      - ./uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
      - database
    command:
      - /bin/sh
      - -c
      - |
        npx directus bootstrap &&
        npx directus schema apply snapshots/latest.yml --yes &&
        npx directus start
    environment:
      EXTENSIONS_AUTO_RELOAD: 'true'

      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'

networks:
  directus:
